image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim

variables:
  UV_CACHE_DIR: .uv-cache  # met le cache dans le projet pour GitLab

cache:
  key:
    files:
      - uv.lock          # le cache est invalidé si le lockfile change
  paths:
    - .uv-cache/

stages:          
  - test
  - lint  
  - build

before_script:
  - uv sync --frozen   # installe exactement ce qui est dans uv.lock


jobs : 
  lint
  runs-on : 